export default {
  asyncFetchContentStarted: 'WIKI_ASYNC_FETCH_CONTENT_STARTED',
  asyncFetchContentDone: 'WIKI_ASYNC_FETCH_CONTENT_DONE',
  asyncFetchContentFailed: 'WIKI_ASYNC_FETCH_CONTENT_FAILED',
  asyncFetchDiffContentStarted: 'WIKI_ASYNC_FETCH_DIFF_CONTENT_STARTED',
  asyncFetchDiffContentDone: 'WIKI_ASYNC_FETCH_DIFF_CONTENT_DONE',
  asyncFetchDiffContentFailed: 'WIKI_ASYNC_FETCH_DIFF_CONTENT_FAILED',
  asyncFetchPageIdStarted: 'WIKI_ASYNC_FETCH_PAGE_ID_STARTED',
  asyncFetchPageIdDone: 'WIKI_ASYNC_FETCH_PAGE_ID_DONE',
  asyncFetchPageIdFailed: 'WIKI_ASYNC_FETCH_PAGE_ID_FAILED',
  asyncFetchRevisionsStarted: 'WIKI_ASYNC_FETCH_REVISIONS_STARTED',
  asyncFetchRevisionsDone: 'WIKI_ASYNC_FETCH_REVISIONS_DONE',
  asyncFetchRevisionsFailed: 'WIKI_ASYNC_FETCH_REVISIONS_FAILED',
  asyncFetchStyleSheetStarted: 'WIKI_ASYNC_FETCH_STYLESHEET_STARTED',
  asyncFetchStyleSheetDone: 'WIKI_ASYNC_FETCH_STYLESHEET_DONE',
  asyncFetchStyleSheetFailed: 'WIKI_ASYNC_FETCH_STYLESHEET_FAILED',
  updateCurrentEntityIdIndex: 'WIKI_UPDATE_CURRENT_ENTITY_ID_INDEX',
  updatePaused: 'WIKI_UPDATE_PAUSED',
} as const;
