export const ACTION_CREATOR_FACTORY_PREFIX = '@@shiranui/HOME';
export const ASYNC_INCREMENT_COUNTER = 'ASYNC_INCREMENT_COUNTER';
export const INCREMENT_COUNTER = 'INCREMENT';
export const DECREMENT_COUNTER = 'DECREMENT';

export default {
  ACTION_CREATOR_FACTORY_PREFIX,
  ASYNC_INCREMENT_COUNTER,
  INCREMENT_COUNTER,
  DECREMENT_COUNTER
};
